stages:
  - deploy

build_citest_env:
  stage: deploy
  script:
    - cp -r /data/gitlab-deploy/config/wilddog-doc4/build-node_modules/node_modules ./
    - hexo clean
    - hexo generate
    - mv public /data/deploy/docs.wilddog.com
    - bash /data/gitlab-deploy/scripts/citest-163_wilddog-doc4.sh
  only:
    - /^stage-.*$/
  except:
    - triggers
  tags:
    - CI-TEST-163

build_pre_env:
  stage: deploy
  script: 
    - cp -r /data/gitlab-deploy/config/wilddog-doc4/build-node_modules/node_modules ./
    - hexo clean
    - hexo generate
    - mv public /data/deploy/docs.wilddog.com
    - bash /data/gitlab-deploy/scripts/pre-1-13_wilddog-doc4.sh
  only:
    - triggers
  except:
    - /^fix-.*$/
    - /^feature-.*$/
    - /^rc-.*/
    - master
  tags:
    - PRE-1.13